### ISSUE TITLE
Use hardcoded Tap Domain Separator from tap-core

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#115]
tap-core has a `tap_eip712_domain` function that uses the hardcoded name and version. We had some problems in the past with mismatch between those, let's just use this function.

[https://docs.rs/tap_core/latest/tap_core/fn.tap_eip712_domain.html](https://docs.rs/tap_core/latest/tap_core/fn.tap_eip712_domain.html)

**Comment by gusinacio** [comment]
We could move the DOMAIN_SEPARATOR to `tap-core` to prevent mismatches on any side.

**Comment by YashBit** [comment]
@gusinacio Please can you assign this to me?

**Comment by gusinacio** [comment]
@YashBit just assigned to you. Also added some description.

**Comment by YashBit** [comment]
@gusinacio Updated where I found variables using the hardcoded values of eip712_domain!

Would appreciate some patience if my corrections are not fully there, I am still new to Rust. Hence, picking a good-first-issue.
