### ISSUE TITLE
Bug: indexer_allocations limited to first 1000

### ISSUE THREAD

**Issue by hopeyen** [graphprotocol/indexer-rs#128]
**Describe the bug**

https://github.com/graphprotocol/indexer-rs/blob/main/common/src/allocations/monitor.rs#L68
This query string limits indexer_allocation query to first 1000 active allocations with no pagination. Shown by an instance that there exists indexer with 1000+ active allocations, this function fails to grab all eligible allocations for monitoring. 

**Expected behavior**
Add pagination to the query and ensure all active allocations for an indexer are monitored.

**Additional context**
Uncovered by the same issue on TS version of indexer-service

**Comment by aasseman** [comment]
Corresponding fix in the TS version: https://github.com/graphprotocol/indexer/pull/862
