### ISSUE TITLE
[Feat] More flexible IndexerServiceMetrics

### ISSUE THREAD

**Issue by hopeyen** [graphprotocol/indexer-rs#136]
**Problem statement**
There's only 3 fields in the metrics tracked. It would be good to have flexibility in this struct so we can add more metrics for individual data services instead of hosting a separate metrics service.

```
pub struct IndexerServiceMetrics {
    pub requests: IntCounterVec,
    pub successful_requests: IntCounterVec,
    pub failed_requests: IntCounterVec,
}
```

**Expectation proposal**

Generic type/field added to `IndexerServiceMetrics` and function to register more metrics.

**Alternative considerations**
We can have a separate metrics server on the data service level, but that structure seems a bit convoluted for the data providers.

**Comment by gusinacio** [comment]
Now metrics are static and can be created anywhere in the code.
