### ISSUE TITLE
Tap-agent crashes if no aggregator URL supplied for all Senders on-chain

### ISSUE THREAD

**Issue by carlosvdr** [graphprotocol/indexer-rs#138]
**Describe the bug**
Tap aggregator breaks by not receving the endpoint of an undesired sender

**To Reproduce**
1. endpoints.yaml is filled with this info:
`0xC3dDf37906724732FfD748057FEBe23379b0710D: "https://tap-subgraph.testnet.thegraph.com"`
Error rises when starting tap-agent:
```
tap-agent-1  | thread 'main' panicked at tap-agent/src/tap/sender_accounts_manager.rs:279:14:
tap-agent-1  | Should be able to update_sender_accounts: No sender_aggregator_endpoint found for sender 0x21FEd3c4340f67DbF2b78c670ebD1940668CA03e
```

**Expected behavior**
Should not crash if there is a sender we dont care for

**Desktop (please complete the following information):**
 - OS: rocky-linux
 - Version 8
 - Rust Version 1.76

**Comment by aasseman** [comment]
The bug seems to be that `tap-agent` tries to match a TAP Aggregator endpoint URL to all the Senders registered on chain, regardless of whether we received receipts.

**Comment by aasseman** [comment]
@gusinacio this https://github.com/graphprotocol/indexer-rs/pull/147 fixed it, right?

**Comment by gusinacio** [comment]
Yes!
