### ISSUE TITLE
[Feat.Req] Be more explicit about not running indexer-rs migrations and relying on indexer-agent

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#141]
**Problem statement**
People are running the sqlx migrations and are getting problems with conflicts on the migrations.

**Expectation proposal**
Be more explicit on the documentation about not running the migrations using sqlx. They are handled by indexer-agent

**Comment by aasseman** [comment]
Seems the issue was not about running the sqlx migrations, but just migrating from indexer-agent v0.21 to the TAP version. We should test this scenario to make sure.
