### ISSUE TITLE
Bug: Escrow Account from common is failing to filter the correct address

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#162]
**Describe the bug**
Escrow Account eventual is using the indexer address as filter and the way graph-node works, everything is supposed to be lowercase

**Comment by aasseman** [comment]
This is already lowercase:
https://github.com/graphprotocol/indexer-rs/blob/1966049e5552eab5aca84f6e49879d3fe1a8db98/common/src/escrow_accounts.rs#L170

Do you have more details about the issue?

**Comment by hopeyen** [comment]
Having trouble reproducing the issue, the gist is that Escrow query returned empty array (no accounts) when I expected at least one for the indexer. 
I can file an issue if it pops up again.

**Comment by aasseman** [comment]
Cannot reproduce for now
