### ISSUE TITLE
[tap-agent] Implement retrieve receipts with limit 

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#193]
There's no implementation for limiting how many receipts are retrieved. 

This is the code:
- https://github.com/graphprotocol/indexer-rs/blob/d3eafbe464b37dd633f336350e2a6041df54144f/tap-agent/src/tap/context/receipt.rs#L93

**Comment by aasseman** [comment]
Reopening #96 (duplicate)
