### ISSUE TITLE
Consider avoiding `Eventual::value_immediate` or mitigate

### ISSUE THREAD

**Issue by aasseman** [graphprotocol/indexer-rs#250]
`value_immediate` is currently used in a few latency-sensitive places.
However this could be a problem if `indexer-service` starts serving queries before the eventuals are ready.

For example we temporarily observed this kind of GraphQL response during testing:
```
{"message":"No attestation signer found for manifest `QmZ7TYJ3ZEakmV1TJCSbZDsv1qaFj41dW31czNs9HptfAC`"}
```
Which could be due to the `attestation_signers` eventual not having finished loading yet:
https://github.com/graphprotocol/indexer-rs/blob/9edb0e5882f3b95de3be2e4296d7aa0719dae8e0/common/src/indexer_service/http/request_handler.rs#L61-L64

**Comment by gusinacio** [comment]
The error happens on 
https://github.com/graphprotocol/indexer-rs/blob/c693f0ebe36a0f5dce8f46fd974eef1a5924c3c6/common/src/indexer_service/http/request_handler.rs#L65-L68.

We need to investigate why it's happening.
