### ISSUE TITLE
Display more information of failed receipts

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#272]
**Describe the bug**
When a receipt fails, we don't know the reason. We want to be able to access the errors and print on the console or even log on to the database.

**Comment by taslimmuhammed** [comment]
getting this error  on running command "cargo run -p service -- --help" to start the project, please tell if I'm starting it wrong. 
![Screenshot from 2024-08-17 15-42-11](https://github.com/user-attachments/assets/1e24fb00-b367-4eea-a2b8-75bd07d3c2ab)

**Comment by gusinacio** [comment]
We are now printing on "debug" mode. Still need some work on the database side.
