### ISSUE TITLE
[Feat.Req] Bulk insert of failed receipts

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#273]
**Problem statement**
We have a loop that inserts all the failed receipts, but it's way more efficient if we insert via bulk.

**Comment by taslimmuhammed** [comment]
Hi, I was willing to contribute, did you meant this part:-
![Screenshot from 2024-07-23 20-09-20](https://github.com/user-attachments/assets/92b0aa6a-fb8e-4eb1-83ab-2dc9595e234e)

**Comment by taslimmuhammed** [comment]
Hi, I was willing to contribute, did you meant this part of the code:-
![Screenshot from 2024-08-31 20-56-51](https://github.com/user-attachments/assets/dc6576d0-e353-4fec-b852-49ac4f68766d)

**Comment by gusinacio** [comment]
> Hi, I was wishing to contribute, did you meant this part of the code:- ![Screenshot from 2024-08-31 20-56-51](https://private-user-images.githubusercontent.com/44280622/363423108-dc6576d0-e353-4fec-b852-49ac4f68766d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2OTM0MDgsIm5iZiI6MTcyNjY5MzEwOCwicGF0aCI6Ii80NDI4MDYyMi8zNjM0MjMxMDgtZGM2NTc2ZDAtZTM1My00ZmVjLWI4NTItNDlhYzRmNjg3NjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDIwNTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MjFlOTk4MmU5MmMyMGJjZWE2OTA3NDI0NDAxMjMwNWFiMzZiOTM4ZThmMDEyNmQyNTA4MzMzNTY2YTkwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GytId8TIPvwIFLwJ_Pcjpihs8dpkX17MJzjaGkViUR4)

Hello @taslimmuhammed, sorry for the late response. So, the expected code for this issue is to use the same type of code on your screenshot but for the invalid/failed receipts.

The code that we'd like to update to look more like the screenshot is located [here](https://github.com/graphprotocol/indexer-rs/blob/18e2609caf42faa547e6f431170358382213c763/tap-agent/src/agent/sender_allocation.rs#L675).

Let me know if you still have plans to contribute.

**Comment by taslimmuhammed** [comment]
thanks for the reply

**Comment by taslimmuhammed** [comment]
could you assign the issue to me, I'll finish it this weekend.

**Comment by taslimmuhammed** [comment]
Hi, when you have time please go through the code
