### ISSUE TITLE
[Feat.Req] Missing metrics from indexer-service

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#274]
**Problem statement**
There are some metrics on indexer-service-ts that are not available on the rust version. We need to add the following:
- Query count with labels subgraph hash, allocation id, sender
- Histograms for execution times (auto metrics does it)

**Comment by calinah** [comment]
yes please

**Comment by cryptovestor21** [comment]
In addition to the above, these metrics help us understand if the gateway is succesfully communicating with our service endpoint
```
indexer_service_cost_model_queries_invalid
indexer_service_cost_model_batch_queries
indexer_service_cost_model_batch_queries_failed
indexer_service_cost_model_batch_queries_invalid
```
