### ISSUE TITLE
Drop eventuals in favor of Tokio watch + timers

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#333]
@Theodus suggested that Eventuals are really hard to debug and we should probably ship a standard solution like the [Gateway currently does](https://github.com/edgeandnode/gateway/blob/main/src/network/service.rs) by using [tokio watch](https://docs.rs/tokio/latest/tokio/sync/watch/index.html).

- [x] #361
- [x] #363
- [x] #364
- [x] #365 
- [x] #440 
- [x] #441

**Comment by taslimmuhammed** [comment]
Hi, can I have this?

**Comment by gusinacio** [comment]
This is a larger refactor that will update multiple parts of the code.

I suggest you starting with only one: `escrow_accounts` or `allocations` and we can split the PR in multiple.

**Comment by gusinacio** [comment]
Actually, to start you can update the dispute manager which is the smallest Eventual in the code.

https://github.com/graphprotocol/indexer-rs/blob/main/common/src/attestations/dispute_manager.rs

**Comment by taslimmuhammed** [comment]
sure, I'll send PR as soon as possible
