### ISSUE TITLE
Add `envsubst` for config files

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#336]
**Problem statement**
Indexers would like to use their own environment variable names within the config instead of relying on config paths, with separators.

**Expectation proposal**
If a config file contains `${VARIABLE}`, it should be replaced correctly with environment variables.

**Additional context**
This would help a lot with indexer migration from indexer-ts to indexer-rs.

**Comment by taslimmuhammed** [comment]
Hi, this [line](https://github.com/graphprotocol/indexer-rs/blob/ad8d4fbfb6cb15b4503e956c09258e7988226169/config/src/config.rs#L71) right?

**Comment by gusinacio** [comment]
> Hi, this [line](https://github.com/graphprotocol/indexer-rs/blob/ad8d4fbfb6cb15b4503e956c09258e7988226169/config/src/config.rs#L71) right?

Yes, we need to update the `parse` function so it replaces the env vars before it's merged by Figment.

**Comment by gusinacio** [comment]
Do you want to give it a try?

**Comment by taslimmuhammed** [comment]
of course, I'll try to send pr asap
