### ISSUE TITLE
Use total receipts outside buffer as a trigger for RAV request

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#351]
**Problem statement**
Currently, most of the RAV are requests at the end of allocations. But it would be nice to have a way to trigger them as soon as they reach the `max_receipts_per_request` value as an additional argument. This is also easier to understand and explain to indexers 

**Expectation proposal** 

We need to update the current `SenderFeeTracker` to maintain the information on the total receipts counter. It should have a way to get the total counter outside the buffer.

Note: you don't need to update the heaviest allocation because we don't need to use the counter information.

The trigger of RAV request should be:

```
match (counter_outside_buffer[allocation] > max_ravs, fee > trigger_value) {
    (true, _) => {
        // trigger rav request for allocation
     }
    (_, true) => {
        // trigger normal rav request for heaviest allocation
    }
    _ => {}
}
```

The following code should be updated:

* Update the `SenderFeeTracker` (and possibly `ExpiringSum`), to keep a counter.
  [https://github.com/graphprotocol/indexer-rs/blob/00af5068486c23d0aa4eddc59a18da0335955e8c/tap-agent/src/agent/sender_fee_tracker.rs#L33-L43](https://github.com/graphprotocol/indexer-rs/blob/00af5068486c23d0aa4eddc59a18da0335955e8c/tap-agent/src/agent/sender_fee_tracker.rs#L33-L43)
* Add a new function `get_counter_outside_buffer(id: Address) -> usize` for `SenderFeeTracker`
* Create a new function that receives an allocation id to trigger a rav and update rav_requester_single to use it.
  [https://github.com/graphprotocol/indexer-rs/blob/00af5068486c23d0aa4eddc59a18da0335955e8c/tap-agent/src/agent/sender_account.rs#L199-L237](https://github.com/graphprotocol/indexer-rs/blob/00af5068486c23d0aa4eddc59a18da0335955e8c/tap-agent/src/agent/sender_account.rs#L199-L237)
* Update trigger conditional
  [https://github.com/graphprotocol/indexer-rs/blob/00af5068486c23d0aa4eddc59a18da0335955e8c/tap-agent/src/agent/sender_account.rs#L623-L625](https://github.com/graphprotocol/indexer-rs/blob/00af5068486c23d0aa4eddc59a18da0335955e8c/tap-agent/src/agent/sender_account.rs#L623-L625)

**Comment by YashBit** [comment]
@gusinacio Is this a good issue for a beginner like me? I would like to try it out. My questions would be:

1. How many estimated hours would this take (assumptions: beginner in the codebase, no background of feat)
2. Will I be able to get some support to solve the issue here?

**Comment by YashBit** [comment]
@gusinacio Please can you assign this to me.

**Comment by gusinacio** [comment]
Hey @YashBit, this one is already scheduled to be solved by our team this week and I feel that this requires deeper knowledge of the codebase. A more challenging issue than the `good-first-issue` (in case you want) is #355. Send a message there in case you want to give it a try.
