### ISSUE TITLE
Drop eventuals in favor of Tokio watch + timers for `disputes`

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#361]
Subissue for #333

This is a larger refactor that will update multiple parts of the code.

I suggest you start with dispute manager which is the smallest Eventual in the code.
https://github.com/graphprotocol/indexer-rs/blob/main/common/src/attestations/dispute_manager.rs

After this, we can have more PRs for  `attestation_signers`, `allocation` and `escrow_account`.

_Originally posted by @gusinacio in https://github.com/graphprotocol/indexer-rs/issues/333#issuecomment-2402390838_

**Comment by gusinacio** [comment]
Hey @taslimmuhammed, I'm creating subissues for each of the eventuals

**Comment by taslimmuhammed** [comment]
ok👍
