### ISSUE TITLE
Drop eventuals in favor of Tokio watch + timers for `attestation_signers`

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#363]
Subissue of #333

**Comment by gusinacio** [comment]
@taslimmuhammed could you send a message here, so I can assign to you?

**Comment by taslimmuhammed** [comment]
sure

**Comment by taslimmuhammed** [comment]
hi, getting two errors on `cargo test`:-
- `test tap::checks::deny_list_check::tests::test_sender_denylist ... FAILED`
- `test tap::checks::deny_list_check::tests::test_sender_denylist_updates ... FAILED `
is it expected?

**Comment by gusinacio** [comment]
No, it's not expected. Our CI is currently passing in those two tests. I can only help you if I have more context about which asserts are failing.

As a rule of thumb for weird cases, I always try to rebuild the database, do a cargo clean and rebuild. Let me know if that works or maybe you could send the whole error logs so I can help you better.

**Comment by taslimmuhammed** [comment]
My bad, sorry, forgot to set DATABASE_URL,
