### ISSUE TITLE
Drop eventuals in favor of Tokio watch + timers for `escrow_accounts`

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#365]
Subissue of #333

**Comment by YashBit** [comment]
@gusinacio Please assign this to me.

**Comment by YashBit** [comment]
@gusinacio Please assign this to me since I will be handling the tokio library.

**Comment by taslimmuhammed** [comment]
Oh, I was about to ask but it's fine👍

**Comment by gusinacio** [comment]
Hey @taslimmuhammed, assigned to you.

**Comment by taslimmuhammed** [comment]
Thanks ❤️
