### ISSUE TITLE
Remove sleeps from tests

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#412]
### Description
We have tons of tests inside tap-agent and indexer-common that uses `sleep` to propagate messages and other stuff. @suchapalaver suggested that we should have a way to wait for a specific update with a timeout. This could be really useful for our actor system that needs to wait for some messages to be propagated and currently we have some non-determinism inside tests because it takes more than the current sleep time.

A second approach is to use channels to wait for messages like we do here:
https://github.com/graphprotocol/indexer-rs/blob/ff06fa688e1cb94de21a2b9882eea1ee7649e7d7/tap-agent/src/agent/sender_allocation.rs#L1048

In any way we should rely less on sleeps with arbitrary values and more in waiting messages and reliable waiting where we do some sleeps for a few times until we got the correct output or fail with a timeout.

### PR Comment
The `sleep` makes things a bit confusing.

You could use something like this:

```rust
async fn wait_for_update(check: &MinimumValue) {
    tokio::time::timeout(Duration::from_secs(1), async {
        while check.cost_model_map.read().unwrap().len() != expected_len {
            sleep(Duration::from_millis(50)).await;
        }
    }).await.unwrap();
}
```

I think the intention is clearer.

_Originally posted by @suchapalaver in https://github.com/graphprotocol/indexer-rs/pull/153#discussion_r1817008135_

**Comment by taslimmuhammed** [comment]
Hi, replacing sleep with meaningful code right?
`let dispute_manager: Receiver<Option<Address>> = dispute_manager(network_subgraph, Duration::from_secs(60));
sleep(Duration::from_millis(50)).await;`
to waiting until it is not `is_none()` right?

**Comment by taslimmuhammed** [comment]
Can I have this?

**Comment by gusinacio** [comment]
> Can I have this?

Hey, I didn't have time to see this during the weekend. I updated the description. This is a test thing, we should have "asserts with timeouts". Instead of using:

```rust
sleep(Duration::from_millis(10)).await;
assert_eq!(a, b);
```

We should have something like this macro or a function:
```rust
assert_eq_with_timeout!(Duration::from_secs(1), a, b);
```

That would execute the following code:

```rust
let _ = tokio::time::timeout(timeout, async {
        while !(a == b) {
            sleep(Duration::from_millis(50)).await;
        }
    }).await;
assert_eq!(a, b, "Timeout assertion");
```

Should I assign you?

**Comment by taslimmuhammed** [comment]
yeah, sure
