### ISSUE TITLE
Use `graphql-client` for status monitor

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#421]
I didn't know that this was using the older query and not `graphql-client`. Need to update this on a future PR.

_Originally posted by @gusinacio in https://github.com/graphprotocol/indexer-rs/pull/413#discussion_r1821212495_

**Comment by taslimmuhammed** [comment]
Hi, can I have this too

**Comment by gusinacio** [comment]
Hey @taslimmuhammed, overall I prefer assigning an issue to someone once we have it merged.

**Comment by taslimmuhammed** [comment]
cool✌️

**Comment by taslimmuhammed** [comment]
Hi, could you assign this to me.

**Comment by gusinacio** [comment]
> Hi, could you assign this to me.

yes sir 🫡
