### ISSUE TITLE
Create `pipe` function in `watcher.rs` and replace usages

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer-rs#456]
For our refactor, I new pipe function would be really helpful to standardize the way we create functions that react to Receiver changes.

              I think `pipe_async` could become a function in our `watcher.rs` and be reused in multiple places.

_Originally posted by @gusinacio in https://github.com/graphprotocol/indexer-rs/pull/413#discussion_r1826030661_

**Comment by taslimmuhammed** [comment]
Hi, please assign me👋
