### ISSUE TITLE
Return syncing status (latest block synced) in header of subgraph query responses

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer-rs#494]
**Problem statement**

Currently the Gateway uses query rewrites to keep track of block numbers on each chain.

**Expectation proposal**

Include header with `latestSyncedBlockNumber` and chainHeadBlock information: `chainHeadBlocknumber`, `chainheadBlockHash`, and `chainHeadBlocktimestamp`.

**Comment by Theodus** [comment]
The requirements can be limited to the block number, hash, and timestamp for the latest indexed block for the subgraph deployment being queried. It's unnecessary for any client to get block info for any block that cannot be queried yet.
