### ISSUE TITLE
[Feat.Req] Check receipt timestamps early

### ISSUE THREAD

**Issue by aasseman** [graphprotocol/indexer-rs#92]
**Problem statement**
We are not checking (in indexer-service) that new receipts have a reasonably accurate timestamp (let's say within 5 seconds of our own clock). So as it is right now it is not really safe :/.

**Expectation proposal**
Check in-band that receipt timestamps are reasonably close to the system clock.

**Additional context**
https://github.com/graphprotocol/indexer-rs/pull/83#discussion_r1380293004

**Comment by gusinacio** [comment]
Closed by #155
