### ISSUE TITLE
Integrate TAP Agent with gateway registry contract

### ISSUE THREAD

**Issue by aasseman** [graphprotocol/indexer-rs#94]
**Problem statement**
Currently the TAP Agent relies on a user-provided list of sender addresses with corresponding TAP aggregator endpoint URLs. This is a stopgap solution for integration testing.

**Expectation proposal**
Once the gateway registry contract is implemented (TBD), TAP Agent will be modified to get the TAP aggregator endpoint URLs from there.

**Alternative considerations**

**Additional context**
https://github.com/graphprotocol/indexer-rs/blob/1178c6386768c98b7efb8463c024c57286ef7d1b/tap-agent/src/agent.rs#L70-L73

**Comment by gusinacio** [comment]
Closing in favor of #342
