### ISSUE TITLE
Implement receipt value check

### ISSUE THREAD

**Issue by aasseman** [graphprotocol/indexer-rs#95]
**Problem statement**
TAP Agent does not currently check that the receipt values are correct w.r.t the query and Agora model.

**Expectation proposal**
Computing a query's price w.r.t. an Agora model is fairly easy on principle, as the canonical Agora implementation already is a Rust library: https://github.com/graphprotocol/agora.

However:
- Indexers can change their Agora models at any time.
- Gateways poll the indexer's models at a regular interval (~30sec).
- The indexer is not informed of which model was used for a particular query (would have to guess by testing its most recent model versions).
- There is no standard currently as to how long a gateway is authorized to use an obsolete model.

**Additional context**
https://github.com/graphprotocol/indexer-rs/blob/1178c6386768c98b7efb8463c024c57286ef7d1b/tap-agent/src/tap/sender_allocation_relationship.rs#L96-L103

**Comment by gusinacio** [comment]
test
