### ISSUE TITLE
Add HTTP request compression to RAV requests

### ISSUE THREAD

**Issue by aasseman** [graphprotocol/indexer-rs#97]
**Problem statement**
The TAP Aggregator API is based on JSON-RPC. Thus there are easy bandwidth gains to be had with request compression since JSON is usually highly compressible.

**Additional context**
https://github.com/graphprotocol/indexer-rs/blob/1178c6386768c98b7efb8463c024c57286ef7d1b/tap-agent/src/tap/sender_allocation_relationship.rs#L297-L302

**Comment by carlosvdr** [comment]
This will be stopped for a bit now, there are several dependencies issues, and they havent pushed and fixed their stuff from main to a newer version, still some stuff need to be fixed, so this should be addressed in some time when those problems from `jsonrpsee` side are solved
